name: Run CI
on:
  push:
    branches-ignore:
      - develop
      - release/**
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["18.0.0", "20.0.0"]
        task: [test]

    runs-on: ${{matrix.os}}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
      - name: Run tests
        env:
          OPENCV4NODEJS_DISABLE_AUTOBUILD: 1
        run: |
          echo installing
          npm install --unsafe-perm
          echo running tests
          cd ./test
          npm install --unsafe-perm
          npm test
          npm run test-externalMemTracking
