name: Create tagged release
on:
  push:
    tags:
      - v*.*.*

jobs:
  prebuild-node:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]
        task: [prebuild]
        runtime: [node]
        target: ["18.0.0", "20.0.0"]
    runs-on: ${{matrix.os}}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
      - name: Install
        run: npm ci --unsafe-perm
      - name: Publish prebuild
        shell: bash
        run: npm run prebuild -- -t ${{matrix.target}} -r ${{matrix.runtime}} --include-regex "\.(node|a|so|dylib|lib|dll).*$" -u ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs:
      - prebuild-node
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Publish tagged release
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
